name: Continous Integration
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      -main
      -dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to current repo
        uses: actions/checkout@v2
      
      - name: Initializes Node js enviornment
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm install 
      
      - name: Run Test
        run: npm test
